# Generated by Django 5.1.6 on 2025-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
