# Generated by Django 5.1.6 on 2025-03-04 19:37

import core.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.generate_random_filename, *(), **{'subdir': 'avatars'})),
        ),
    ]
