services:
  web:
    container_name: strvsocial-web
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  tailwind:
    container_name: strvsocial-tailwind
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true
    restart: always

  db:
    container_name: strvsocial-db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=strvsocial
      - POSTGRES_PASSWORD=strvsocial
      - POSTGRES_DB=strvsocial

  redis:
    container_name: strvsocial-redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
