# Generated by Django 5.1.6 on 2025-03-04 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Text Content')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('gif', 'GIF'), ('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], max_length=10, verbose_name='Media Type')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Media File')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Embedding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
