# Generated by Django 5.1.6 on 2025-03-04 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_content_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentPost',
        ),
        migrations.AlterModelOptions(
            name='contentpost',
            options={'get_latest_by': 'updated_at', 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
    ]
