# Generated by Django 5.1.6 on 2025-03-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contentpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpost',
            options={'get_latest_by': 'updated_at', 'ordering': ['-created_at'], 'verbose_name': 'Content Post', 'verbose_name_plural': 'Content Posts'},
        ),
    ]
